#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("stream_in_TDATA", 24, hls_in, 0, "axis", "in_data", 1),
	Port_Property("stream_in_TKEEP", 3, hls_in, 1, "axis", "in_data", 1),
	Port_Property("stream_in_TSTRB", 3, hls_in, 2, "axis", "in_data", 1),
	Port_Property("stream_in_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("stream_in_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("stream_in_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("stream_in_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("stream_out_TDATA", 24, hls_out, 7, "axis", "out_data", 1),
	Port_Property("stream_out_TKEEP", 3, hls_out, 8, "axis", "out_data", 1),
	Port_Property("stream_out_TSTRB", 3, hls_out, 9, "axis", "out_data", 1),
	Port_Property("stream_out_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("stream_out_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("stream_out_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("stream_out_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("brightness_V", 4, hls_in, 14, "ap_stable", "in_data", 1),
	Port_Property("color_correct_V", 1, hls_in, 15, "ap_stable", "in_data", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("stream_in_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("stream_in_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("stream_out_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("stream_out_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "hls_video_processor";
