// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_loop_height_pro (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        img_adjusted_data_stream_0_V_dout,
        img_adjusted_data_stream_0_V_empty_n,
        img_adjusted_data_stream_0_V_read,
        img_adjusted_data_stream_1_V_dout,
        img_adjusted_data_stream_1_V_empty_n,
        img_adjusted_data_stream_1_V_read,
        img_adjusted_data_stream_2_V_dout,
        img_adjusted_data_stream_2_V_empty_n,
        img_adjusted_data_stream_2_V_read,
        img_out_data_stream_0_V_din,
        img_out_data_stream_0_V_full_n,
        img_out_data_stream_0_V_write,
        img_out_data_stream_1_V_din,
        img_out_data_stream_1_V_full_n,
        img_out_data_stream_1_V_write,
        img_out_data_stream_2_V_din,
        img_out_data_stream_2_V_full_n,
        img_out_data_stream_2_V_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [31:0] img_adjusted_data_stream_0_V_dout;
input   img_adjusted_data_stream_0_V_empty_n;
output   img_adjusted_data_stream_0_V_read;
input  [31:0] img_adjusted_data_stream_1_V_dout;
input   img_adjusted_data_stream_1_V_empty_n;
output   img_adjusted_data_stream_1_V_read;
input  [31:0] img_adjusted_data_stream_2_V_dout;
input   img_adjusted_data_stream_2_V_empty_n;
output   img_adjusted_data_stream_2_V_read;
output  [7:0] img_out_data_stream_0_V_din;
input   img_out_data_stream_0_V_full_n;
output   img_out_data_stream_0_V_write;
output  [7:0] img_out_data_stream_1_V_din;
input   img_out_data_stream_1_V_full_n;
output   img_out_data_stream_1_V_write;
output  [7:0] img_out_data_stream_2_V_din;
input   img_out_data_stream_2_V_full_n;
output   img_out_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg img_adjusted_data_stream_0_V_read;
reg img_adjusted_data_stream_1_V_read;
reg img_adjusted_data_stream_2_V_read;
reg img_out_data_stream_0_V_write;
reg img_out_data_stream_1_V_write;
reg img_out_data_stream_2_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    img_adjusted_data_stream_0_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] exitcond_i1_reg_199;
reg    img_adjusted_data_stream_1_V_blk_n;
reg    img_adjusted_data_stream_2_V_blk_n;
reg    img_out_data_stream_0_V_blk_n;
reg    img_out_data_stream_1_V_blk_n;
reg    img_out_data_stream_2_V_blk_n;
reg   [5:0] t_V_2_reg_122;
wire   [0:0] exitcond113_i1_fu_133_p2;
wire    ap_CS_fsm_state2;
wire   [4:0] r_V_fu_139_p2;
reg   [4:0] r_V_reg_194;
wire   [0:0] exitcond_i1_fu_145_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] c_V_fu_151_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [4:0] t_V_reg_111;
reg    ap_block_state1;
wire    ap_CS_fsm_state5;
reg    ap_block_pp0_stage0_01001;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond113_i1_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((exitcond113_i1_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((exitcond113_i1_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_i1_fu_145_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_V_2_reg_122 <= c_V_fu_151_p2;
    end else if (((exitcond113_i1_fu_133_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        t_V_2_reg_122 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t_V_reg_111 <= r_V_reg_194;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_111 <= 5'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_i1_reg_199 <= exitcond_i1_fu_145_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_reg_194 <= r_V_fu_139_p2;
    end
end

always @ (*) begin
    if ((exitcond_i1_fu_145_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond113_i1_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_adjusted_data_stream_0_V_blk_n = img_adjusted_data_stream_0_V_empty_n;
    end else begin
        img_adjusted_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_adjusted_data_stream_0_V_read = 1'b1;
    end else begin
        img_adjusted_data_stream_0_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_adjusted_data_stream_1_V_blk_n = img_adjusted_data_stream_1_V_empty_n;
    end else begin
        img_adjusted_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_adjusted_data_stream_1_V_read = 1'b1;
    end else begin
        img_adjusted_data_stream_1_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_adjusted_data_stream_2_V_blk_n = img_adjusted_data_stream_2_V_empty_n;
    end else begin
        img_adjusted_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_adjusted_data_stream_2_V_read = 1'b1;
    end else begin
        img_adjusted_data_stream_2_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_out_data_stream_0_V_blk_n = img_out_data_stream_0_V_full_n;
    end else begin
        img_out_data_stream_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_out_data_stream_0_V_write = 1'b1;
    end else begin
        img_out_data_stream_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_out_data_stream_1_V_blk_n = img_out_data_stream_1_V_full_n;
    end else begin
        img_out_data_stream_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_out_data_stream_1_V_write = 1'b1;
    end else begin
        img_out_data_stream_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_out_data_stream_2_V_blk_n = img_out_data_stream_2_V_full_n;
    end else begin
        img_out_data_stream_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((exitcond_i1_reg_199 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_out_data_stream_2_V_write = 1'b1;
    end else begin
        img_out_data_stream_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond113_i1_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond113_i1_fu_133_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_i1_fu_145_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_i1_fu_145_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_2_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_1_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_0_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_0_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_2_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_1_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_0_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_0_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & (((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_2_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_1_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_0_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_0_V_empty_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_2_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_1_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_out_data_stream_0_V_full_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_2_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_1_V_empty_n == 1'b0)) | ((exitcond_i1_reg_199 == 1'd0) & (img_adjusted_data_stream_0_V_empty_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign c_V_fu_151_p2 = (t_V_2_reg_122 + 6'd1);

assign exitcond113_i1_fu_133_p2 = ((t_V_reg_111 == 5'd30) ? 1'b1 : 1'b0);

assign exitcond_i1_fu_145_p2 = ((t_V_2_reg_122 == 6'd60) ? 1'b1 : 1'b0);

assign img_out_data_stream_0_V_din = {{img_adjusted_data_stream_0_V_dout[11:4]}};

assign img_out_data_stream_1_V_din = {{img_adjusted_data_stream_1_V_dout[11:4]}};

assign img_out_data_stream_2_V_din = {{img_adjusted_data_stream_2_V_dout[11:4]}};

assign r_V_fu_139_p2 = (t_V_reg_111 + 5'd1);

assign start_out = real_start;

endmodule //Loop_loop_height_pro
