// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module Loop_loop_height_pro_2 (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        img_input_cols_V_c20_dout,
        img_input_cols_V_c20_empty_n,
        img_input_cols_V_c20_read,
        extLd_loc_channel,
        img_input_data_strea_dout,
        img_input_data_strea_empty_n,
        img_input_data_strea_read,
        img_input_data_strea_1_dout,
        img_input_data_strea_1_empty_n,
        img_input_data_strea_1_read,
        img_input_data_strea_2_dout,
        img_input_data_strea_2_empty_n,
        img_input_data_strea_2_read,
        img_crop_data_stream_din,
        img_crop_data_stream_full_n,
        img_crop_data_stream_write,
        img_crop_data_stream_1_din,
        img_crop_data_stream_1_full_n,
        img_crop_data_stream_1_write,
        img_crop_data_stream_2_din,
        img_crop_data_stream_2_full_n,
        img_crop_data_stream_2_write
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_pp0_stage0 = 4'd4;
parameter    ap_ST_fsm_state5 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [11:0] img_input_cols_V_c20_dout;
input   img_input_cols_V_c20_empty_n;
output   img_input_cols_V_c20_read;
input  [11:0] extLd_loc_channel;
input  [7:0] img_input_data_strea_dout;
input   img_input_data_strea_empty_n;
output   img_input_data_strea_read;
input  [7:0] img_input_data_strea_1_dout;
input   img_input_data_strea_1_empty_n;
output   img_input_data_strea_1_read;
input  [7:0] img_input_data_strea_2_dout;
input   img_input_data_strea_2_empty_n;
output   img_input_data_strea_2_read;
output  [7:0] img_crop_data_stream_din;
input   img_crop_data_stream_full_n;
output   img_crop_data_stream_write;
output  [7:0] img_crop_data_stream_1_din;
input   img_crop_data_stream_1_full_n;
output   img_crop_data_stream_1_write;
output  [7:0] img_crop_data_stream_2_din;
input   img_crop_data_stream_2_full_n;
output   img_crop_data_stream_2_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg img_input_cols_V_c20_read;
reg img_input_data_strea_read;
reg img_input_data_strea_1_read;
reg img_input_data_strea_2_read;
reg img_crop_data_stream_write;
reg img_crop_data_stream_1_write;
reg img_crop_data_stream_2_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg    img_input_cols_V_c20_blk_n;
reg    img_input_data_strea_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg    img_input_data_strea_1_blk_n;
reg    img_input_data_strea_2_blk_n;
reg    img_crop_data_stream_blk_n;
reg   [0:0] or_cond_i_i_i_i_reg_211;
reg    img_crop_data_stream_1_blk_n;
reg    img_crop_data_stream_2_blk_n;
reg   [31:0] t_V_4_reg_133;
wire  signed [31:0] p_read_cast_i_fu_144_p1;
reg  signed [31:0] p_read_cast_i_reg_192;
reg    ap_block_state1;
wire  signed [31:0] cols_V_fu_148_p1;
reg  signed [31:0] cols_V_reg_197;
wire   [0:0] exitcond89_i_i_i_i_fu_152_p2;
wire    ap_CS_fsm_state2;
wire   [31:0] r_V_fu_157_p2;
reg   [31:0] r_V_reg_206;
wire   [0:0] or_cond_i_i_i_i_fu_175_p2;
wire   [0:0] exitcond_i_i_i_i_fu_181_p2;
wire    ap_block_state3_pp0_stage0_iter0;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] c_V_fu_186_p2;
reg    ap_enable_reg_pp0_iter0;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state3;
reg   [31:0] t_V_reg_122;
wire    ap_CS_fsm_state5;
reg    ap_block_pp0_stage0_01001;
wire   [0:0] tmp_i_i_i_fu_163_p2;
wire   [0:0] tmp_i_i_i_59_fu_169_p2;
reg   [3:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((exitcond89_i_i_i_i_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond89_i_i_i_i_fu_152_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_condition_pp0_exit_iter0_state3) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state3);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond89_i_i_i_i_fu_152_p2 == 1'd0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (exitcond_i_i_i_i_fu_181_p2 == 1'd0))) begin
        t_V_4_reg_133 <= c_V_fu_186_p2;
    end else if (((1'b1 == ap_CS_fsm_state2) & (exitcond89_i_i_i_i_fu_152_p2 == 1'd0))) begin
        t_V_4_reg_133 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t_V_reg_122 <= r_V_reg_206;
    end else if ((~((img_input_cols_V_c20_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        t_V_reg_122 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((img_input_cols_V_c20_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        cols_V_reg_197 <= cols_V_fu_148_p1;
        p_read_cast_i_reg_192 <= p_read_cast_i_fu_144_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state2) & (exitcond89_i_i_i_i_fu_152_p2 == 1'd0))) begin
        or_cond_i_i_i_i_reg_211 <= or_cond_i_i_i_i_fu_175_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        r_V_reg_206 <= r_V_fu_157_p2;
    end
end

always @ (*) begin
    if ((exitcond_i_i_i_i_fu_181_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state3 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state3 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond89_i_i_i_i_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_crop_data_stream_1_blk_n = img_crop_data_stream_1_full_n;
    end else begin
        img_crop_data_stream_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_crop_data_stream_1_write = 1'b1;
    end else begin
        img_crop_data_stream_1_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_crop_data_stream_2_blk_n = img_crop_data_stream_2_full_n;
    end else begin
        img_crop_data_stream_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_crop_data_stream_2_write = 1'b1;
    end else begin
        img_crop_data_stream_2_write = 1'b0;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_crop_data_stream_blk_n = img_crop_data_stream_full_n;
    end else begin
        img_crop_data_stream_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((or_cond_i_i_i_i_reg_211 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_crop_data_stream_write = 1'b1;
    end else begin
        img_crop_data_stream_write = 1'b0;
    end
end

always @ (*) begin
    if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_input_cols_V_c20_blk_n = img_input_cols_V_c20_empty_n;
    end else begin
        img_input_cols_V_c20_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((img_input_cols_V_c20_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        img_input_cols_V_c20_read = 1'b1;
    end else begin
        img_input_cols_V_c20_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_input_data_strea_1_blk_n = img_input_data_strea_1_empty_n;
    end else begin
        img_input_data_strea_1_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_input_data_strea_1_read = 1'b1;
    end else begin
        img_input_data_strea_1_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_input_data_strea_2_blk_n = img_input_data_strea_2_empty_n;
    end else begin
        img_input_data_strea_2_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_input_data_strea_2_read = 1'b1;
    end else begin
        img_input_data_strea_2_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        img_input_data_strea_blk_n = img_input_data_strea_empty_n;
    end else begin
        img_input_data_strea_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        img_input_data_strea_read = 1'b1;
    end else begin
        img_input_data_strea_read = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond89_i_i_i_i_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((img_input_cols_V_c20_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond89_i_i_i_i_fu_152_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((exitcond_i_i_i_i_fu_181_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((exitcond_i_i_i_i_fu_181_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_input_data_strea_2_empty_n == 1'b0) | (img_input_data_strea_1_empty_n == 1'b0) | (img_input_data_strea_empty_n == 1'b0) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_2_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_1_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_input_data_strea_2_empty_n == 1'b0) | (img_input_data_strea_1_empty_n == 1'b0) | (img_input_data_strea_empty_n == 1'b0) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_2_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_1_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter1 == 1'b1) & ((img_input_data_strea_2_empty_n == 1'b0) | (img_input_data_strea_1_empty_n == 1'b0) | (img_input_data_strea_empty_n == 1'b0) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_2_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_1_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_full_n == 1'b0))));
end

always @ (*) begin
    ap_block_state1 = ((img_input_cols_V_c20_empty_n == 1'b0) | (real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state3_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = ((img_input_data_strea_2_empty_n == 1'b0) | (img_input_data_strea_1_empty_n == 1'b0) | (img_input_data_strea_empty_n == 1'b0) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_2_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_1_full_n == 1'b0)) | ((or_cond_i_i_i_i_reg_211 == 1'd1) & (img_crop_data_stream_full_n == 1'b0)));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_ready = internal_ap_ready;

assign c_V_fu_186_p2 = (t_V_4_reg_133 + 32'd1);

assign cols_V_fu_148_p1 = $signed(img_input_cols_V_c20_dout);

assign exitcond89_i_i_i_i_fu_152_p2 = ((t_V_reg_122 == p_read_cast_i_reg_192) ? 1'b1 : 1'b0);

assign exitcond_i_i_i_i_fu_181_p2 = ((t_V_4_reg_133 == cols_V_reg_197) ? 1'b1 : 1'b0);

assign img_crop_data_stream_1_din = img_input_data_strea_1_dout;

assign img_crop_data_stream_2_din = img_input_data_strea_2_dout;

assign img_crop_data_stream_din = img_input_data_strea_dout;

assign or_cond_i_i_i_i_fu_175_p2 = (tmp_i_i_i_fu_163_p2 & tmp_i_i_i_59_fu_169_p2);

assign p_read_cast_i_fu_144_p1 = $signed(extLd_loc_channel);

assign r_V_fu_157_p2 = (t_V_reg_122 + 32'd1);

assign start_out = real_start;

assign tmp_i_i_i_59_fu_169_p2 = ((t_V_reg_122 < 32'd1020) ? 1'b1 : 1'b0);

assign tmp_i_i_i_fu_163_p2 = ((t_V_reg_122 > 32'd59) ? 1'b1 : 1'b0);

endmodule //Loop_loop_height_pro_2
