// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="hls_video_processor,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020clg400-1,HLS_INPUT_CLOCK=6.600000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.775000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=8,HLS_SYN_DSP=6,HLS_SYN_FF=2804,HLS_SYN_LUT=3537,HLS_VERSION=2018_3}" *)

module hls_video_processor (
        stream_in_TDATA,
        stream_in_TKEEP,
        stream_in_TSTRB,
        stream_in_TUSER,
        stream_in_TLAST,
        stream_in_TID,
        stream_in_TDEST,
        stream_out_TDATA,
        stream_out_TKEEP,
        stream_out_TSTRB,
        stream_out_TUSER,
        stream_out_TLAST,
        stream_out_TID,
        stream_out_TDEST,
        brightness_V,
        color_correct_V,
        ap_clk,
        ap_rst_n,
        stream_in_TVALID,
        stream_in_TREADY,
        stream_out_TVALID,
        stream_out_TREADY
);


input  [23:0] stream_in_TDATA;
input  [2:0] stream_in_TKEEP;
input  [2:0] stream_in_TSTRB;
input  [0:0] stream_in_TUSER;
input  [0:0] stream_in_TLAST;
input  [0:0] stream_in_TID;
input  [0:0] stream_in_TDEST;
output  [23:0] stream_out_TDATA;
output  [2:0] stream_out_TKEEP;
output  [2:0] stream_out_TSTRB;
output  [0:0] stream_out_TUSER;
output  [0:0] stream_out_TLAST;
output  [0:0] stream_out_TID;
output  [0:0] stream_out_TDEST;
input  [3:0] brightness_V;
input  [0:0] color_correct_V;
input   ap_clk;
input   ap_rst_n;
input   stream_in_TVALID;
output   stream_in_TREADY;
output   stream_out_TVALID;
input   stream_out_TREADY;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire    Block_proc_U0_start_out;
wire    Block_proc_U0_start_write;
wire   [11:0] Block_proc_U0_img_input_rows_V_out_din;
wire    Block_proc_U0_img_input_rows_V_out_write;
wire   [11:0] Block_proc_U0_img_input_rows_V_out1_din;
wire    Block_proc_U0_img_input_rows_V_out1_write;
wire   [11:0] Block_proc_U0_img_input_cols_V_out_din;
wire    Block_proc_U0_img_input_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_stream_in_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [11:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    Block_proc55_U0_ap_start;
wire    Block_proc55_U0_ap_done;
wire    Block_proc55_U0_ap_continue;
wire    Block_proc55_U0_ap_idle;
wire    Block_proc55_U0_ap_ready;
wire    Block_proc55_U0_img_input_rows_V_read;
wire   [11:0] Block_proc55_U0_ap_return;
wire    ap_channel_done_extLd_loc_channel;
wire    extLd_loc_channel_full_n;
wire    Loop_loop_height_pro_2_U0_ap_start;
wire    Loop_loop_height_pro_2_U0_ap_done;
wire    Loop_loop_height_pro_2_U0_ap_continue;
wire    Loop_loop_height_pro_2_U0_ap_idle;
wire    Loop_loop_height_pro_2_U0_ap_ready;
wire    Loop_loop_height_pro_2_U0_start_out;
wire    Loop_loop_height_pro_2_U0_start_write;
wire    Loop_loop_height_pro_2_U0_img_input_cols_V_c20_read;
wire    Loop_loop_height_pro_2_U0_img_input_data_strea_read;
wire    Loop_loop_height_pro_2_U0_img_input_data_strea_1_read;
wire    Loop_loop_height_pro_2_U0_img_input_data_strea_2_read;
wire   [7:0] Loop_loop_height_pro_2_U0_img_crop_data_stream_din;
wire    Loop_loop_height_pro_2_U0_img_crop_data_stream_write;
wire   [7:0] Loop_loop_height_pro_2_U0_img_crop_data_stream_1_din;
wire    Loop_loop_height_pro_2_U0_img_crop_data_stream_1_write;
wire   [7:0] Loop_loop_height_pro_2_U0_img_crop_data_stream_2_din;
wire    Loop_loop_height_pro_2_U0_img_crop_data_stream_2_write;
wire    Loop_loop_height_pro_1_U0_ap_start;
wire    Loop_loop_height_pro_1_U0_ap_done;
wire    Loop_loop_height_pro_1_U0_ap_continue;
wire    Loop_loop_height_pro_1_U0_ap_idle;
wire    Loop_loop_height_pro_1_U0_ap_ready;
wire    Loop_loop_height_pro_1_U0_start_out;
wire    Loop_loop_height_pro_1_U0_start_write;
wire    Loop_loop_height_pro_1_U0_img_crop_data_stream_0_V_read;
wire    Loop_loop_height_pro_1_U0_img_crop_data_stream_1_V_read;
wire    Loop_loop_height_pro_1_U0_img_crop_data_stream_2_V_read;
wire   [31:0] Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_din;
wire    Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_write;
wire   [31:0] Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_din;
wire    Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_write;
wire   [31:0] Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_din;
wire    Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_write;
wire    video_scale_U0_ap_start;
wire    video_scale_U0_ap_done;
wire    video_scale_U0_ap_continue;
wire    video_scale_U0_ap_idle;
wire    video_scale_U0_ap_ready;
wire    video_scale_U0_start_out;
wire    video_scale_U0_start_write;
wire    video_scale_U0_src_data_stream_0_V_read;
wire    video_scale_U0_src_data_stream_1_V_read;
wire    video_scale_U0_src_data_stream_2_V_read;
wire   [31:0] video_scale_U0_dst_data_stream_0_V_din;
wire    video_scale_U0_dst_data_stream_0_V_write;
wire   [31:0] video_scale_U0_dst_data_stream_1_V_din;
wire    video_scale_U0_dst_data_stream_1_V_write;
wire   [31:0] video_scale_U0_dst_data_stream_2_V_din;
wire    video_scale_U0_dst_data_stream_2_V_write;
wire    brightness_color_adj_U0_ap_start;
wire    brightness_color_adj_U0_ap_done;
wire    brightness_color_adj_U0_ap_continue;
wire    brightness_color_adj_U0_ap_idle;
wire    brightness_color_adj_U0_ap_ready;
wire    brightness_color_adj_U0_start_out;
wire    brightness_color_adj_U0_start_write;
wire    brightness_color_adj_U0_src_data_stream_0_V_read;
wire    brightness_color_adj_U0_src_data_stream_1_V_read;
wire    brightness_color_adj_U0_src_data_stream_2_V_read;
wire   [31:0] brightness_color_adj_U0_dst_data_stream_0_V_din;
wire    brightness_color_adj_U0_dst_data_stream_0_V_write;
wire   [31:0] brightness_color_adj_U0_dst_data_stream_1_V_din;
wire    brightness_color_adj_U0_dst_data_stream_1_V_write;
wire   [31:0] brightness_color_adj_U0_dst_data_stream_2_V_din;
wire    brightness_color_adj_U0_dst_data_stream_2_V_write;
wire    Loop_loop_height_pro_U0_ap_start;
wire    Loop_loop_height_pro_U0_ap_done;
wire    Loop_loop_height_pro_U0_ap_continue;
wire    Loop_loop_height_pro_U0_ap_idle;
wire    Loop_loop_height_pro_U0_ap_ready;
wire    Loop_loop_height_pro_U0_start_out;
wire    Loop_loop_height_pro_U0_start_write;
wire    Loop_loop_height_pro_U0_img_adjusted_data_stream_0_V_read;
wire    Loop_loop_height_pro_U0_img_adjusted_data_stream_1_V_read;
wire    Loop_loop_height_pro_U0_img_adjusted_data_stream_2_V_read;
wire   [7:0] Loop_loop_height_pro_U0_img_out_data_stream_0_V_din;
wire    Loop_loop_height_pro_U0_img_out_data_stream_0_V_write;
wire   [7:0] Loop_loop_height_pro_U0_img_out_data_stream_1_V_din;
wire    Loop_loop_height_pro_U0_img_out_data_stream_1_V_write;
wire   [7:0] Loop_loop_height_pro_U0_img_out_data_stream_2_V_din;
wire    Loop_loop_height_pro_U0_img_out_data_stream_2_V_write;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] Mat2AXIvideo_U0_stream_out_TDATA;
wire    Mat2AXIvideo_U0_stream_out_TVALID;
wire   [2:0] Mat2AXIvideo_U0_stream_out_TKEEP;
wire   [2:0] Mat2AXIvideo_U0_stream_out_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_stream_out_TUSER;
wire   [0:0] Mat2AXIvideo_U0_stream_out_TLAST;
wire   [0:0] Mat2AXIvideo_U0_stream_out_TID;
wire   [0:0] Mat2AXIvideo_U0_stream_out_TDEST;
wire    ap_sync_continue;
wire    img_input_rows_V_c_full_n;
wire   [11:0] img_input_rows_V_c_dout;
wire    img_input_rows_V_c_empty_n;
wire    img_input_rows_V_c20_full_n;
wire   [11:0] img_input_rows_V_c20_dout;
wire    img_input_rows_V_c20_empty_n;
wire    img_input_cols_V_c_full_n;
wire   [11:0] img_input_cols_V_c_dout;
wire    img_input_cols_V_c_empty_n;
wire    img_input_data_strea_full_n;
wire   [7:0] img_input_data_strea_dout;
wire    img_input_data_strea_empty_n;
wire    img_input_data_strea_1_full_n;
wire   [7:0] img_input_data_strea_1_dout;
wire    img_input_data_strea_1_empty_n;
wire    img_input_data_strea_2_full_n;
wire   [7:0] img_input_data_strea_2_dout;
wire    img_input_data_strea_2_empty_n;
wire    img_input_cols_V_c20_full_n;
wire   [11:0] img_input_cols_V_c20_dout;
wire    img_input_cols_V_c20_empty_n;
wire   [11:0] extLd_loc_channel_dout;
wire    extLd_loc_channel_empty_n;
wire    img_crop_data_stream_full_n;
wire   [7:0] img_crop_data_stream_dout;
wire    img_crop_data_stream_empty_n;
wire    img_crop_data_stream_1_full_n;
wire   [7:0] img_crop_data_stream_1_dout;
wire    img_crop_data_stream_1_empty_n;
wire    img_crop_data_stream_2_full_n;
wire   [7:0] img_crop_data_stream_2_dout;
wire    img_crop_data_stream_2_empty_n;
wire    img_nogamma_data_str_full_n;
wire   [31:0] img_nogamma_data_str_dout;
wire    img_nogamma_data_str_empty_n;
wire    img_nogamma_data_str_1_full_n;
wire   [31:0] img_nogamma_data_str_1_dout;
wire    img_nogamma_data_str_1_empty_n;
wire    img_nogamma_data_str_2_full_n;
wire   [31:0] img_nogamma_data_str_2_dout;
wire    img_nogamma_data_str_2_empty_n;
wire    img_scaled_data_stre_full_n;
wire   [31:0] img_scaled_data_stre_dout;
wire    img_scaled_data_stre_empty_n;
wire    img_scaled_data_stre_1_full_n;
wire   [31:0] img_scaled_data_stre_1_dout;
wire    img_scaled_data_stre_1_empty_n;
wire    img_scaled_data_stre_2_full_n;
wire   [31:0] img_scaled_data_stre_2_dout;
wire    img_scaled_data_stre_2_empty_n;
wire    img_adjusted_data_st_full_n;
wire   [31:0] img_adjusted_data_st_dout;
wire    img_adjusted_data_st_empty_n;
wire    img_adjusted_data_st_1_full_n;
wire   [31:0] img_adjusted_data_st_1_dout;
wire    img_adjusted_data_st_1_empty_n;
wire    img_adjusted_data_st_2_full_n;
wire   [31:0] img_adjusted_data_st_2_dout;
wire    img_adjusted_data_st_2_empty_n;
wire    img_out_data_stream_s_full_n;
wire   [7:0] img_out_data_stream_s_dout;
wire    img_out_data_stream_s_empty_n;
wire    img_out_data_stream_1_full_n;
wire   [7:0] img_out_data_stream_1_dout;
wire    img_out_data_stream_1_empty_n;
wire    img_out_data_stream_2_full_n;
wire   [7:0] img_out_data_stream_2_dout;
wire    img_out_data_stream_2_empty_n;
wire   [0:0] start_for_Block_proc55_U0_din;
wire    start_for_Block_proc55_U0_full_n;
wire   [0:0] start_for_Block_proc55_U0_dout;
wire    start_for_Block_proc55_U0_empty_n;
wire    AXIvideo2Mat_U0_start_full_n;
wire    AXIvideo2Mat_U0_start_write;
wire    Block_proc55_U0_start_full_n;
wire    Block_proc55_U0_start_write;
wire   [0:0] start_for_Loop_loop_height_pro_1_U0_din;
wire    start_for_Loop_loop_height_pro_1_U0_full_n;
wire   [0:0] start_for_Loop_loop_height_pro_1_U0_dout;
wire    start_for_Loop_loop_height_pro_1_U0_empty_n;
wire   [0:0] start_for_video_scale_U0_din;
wire    start_for_video_scale_U0_full_n;
wire   [0:0] start_for_video_scale_U0_dout;
wire    start_for_video_scale_U0_empty_n;
wire   [0:0] start_for_brightness_color_adj_U0_din;
wire    start_for_brightness_color_adj_U0_full_n;
wire   [0:0] start_for_brightness_color_adj_U0_dout;
wire    start_for_brightness_color_adj_U0_empty_n;
wire   [0:0] start_for_Loop_loop_height_pro_U0_din;
wire    start_for_Loop_loop_height_pro_U0_full_n;
wire   [0:0] start_for_Loop_loop_height_pro_U0_dout;
wire    start_for_Loop_loop_height_pro_U0_empty_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .start_full_n(start_for_Block_proc55_U0_full_n),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .start_out(Block_proc_U0_start_out),
    .start_write(Block_proc_U0_start_write),
    .img_input_rows_V_out_din(Block_proc_U0_img_input_rows_V_out_din),
    .img_input_rows_V_out_full_n(img_input_rows_V_c_full_n),
    .img_input_rows_V_out_write(Block_proc_U0_img_input_rows_V_out_write),
    .img_input_rows_V_out1_din(Block_proc_U0_img_input_rows_V_out1_din),
    .img_input_rows_V_out1_full_n(img_input_rows_V_c20_full_n),
    .img_input_rows_V_out1_write(Block_proc_U0_img_input_rows_V_out1_write),
    .img_input_cols_V_out_din(Block_proc_U0_img_input_cols_V_out_din),
    .img_input_cols_V_out_full_n(img_input_cols_V_c_full_n),
    .img_input_cols_V_out_write(Block_proc_U0_img_input_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .stream_in_TDATA(stream_in_TDATA),
    .stream_in_TVALID(stream_in_TVALID),
    .stream_in_TREADY(AXIvideo2Mat_U0_stream_in_TREADY),
    .stream_in_TKEEP(stream_in_TKEEP),
    .stream_in_TSTRB(stream_in_TSTRB),
    .stream_in_TUSER(stream_in_TUSER),
    .stream_in_TLAST(stream_in_TLAST),
    .stream_in_TID(stream_in_TID),
    .stream_in_TDEST(stream_in_TDEST),
    .img_rows_V_dout(img_input_rows_V_c_dout),
    .img_rows_V_empty_n(img_input_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(img_input_cols_V_c_dout),
    .img_cols_V_empty_n(img_input_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(img_input_data_strea_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(img_input_data_strea_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(img_input_data_strea_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(img_input_cols_V_c20_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

Block_proc55 Block_proc55_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc55_U0_ap_start),
    .ap_done(Block_proc55_U0_ap_done),
    .ap_continue(Block_proc55_U0_ap_continue),
    .ap_idle(Block_proc55_U0_ap_idle),
    .ap_ready(Block_proc55_U0_ap_ready),
    .img_input_rows_V_dout(img_input_rows_V_c20_dout),
    .img_input_rows_V_empty_n(img_input_rows_V_c20_empty_n),
    .img_input_rows_V_read(Block_proc55_U0_img_input_rows_V_read),
    .ap_return(Block_proc55_U0_ap_return)
);

Loop_loop_height_pro_2 Loop_loop_height_pro_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_loop_height_pro_2_U0_ap_start),
    .start_full_n(start_for_Loop_loop_height_pro_1_U0_full_n),
    .ap_done(Loop_loop_height_pro_2_U0_ap_done),
    .ap_continue(Loop_loop_height_pro_2_U0_ap_continue),
    .ap_idle(Loop_loop_height_pro_2_U0_ap_idle),
    .ap_ready(Loop_loop_height_pro_2_U0_ap_ready),
    .start_out(Loop_loop_height_pro_2_U0_start_out),
    .start_write(Loop_loop_height_pro_2_U0_start_write),
    .img_input_cols_V_c20_dout(img_input_cols_V_c20_dout),
    .img_input_cols_V_c20_empty_n(img_input_cols_V_c20_empty_n),
    .img_input_cols_V_c20_read(Loop_loop_height_pro_2_U0_img_input_cols_V_c20_read),
    .extLd_loc_channel(extLd_loc_channel_dout),
    .img_input_data_strea_dout(img_input_data_strea_dout),
    .img_input_data_strea_empty_n(img_input_data_strea_empty_n),
    .img_input_data_strea_read(Loop_loop_height_pro_2_U0_img_input_data_strea_read),
    .img_input_data_strea_1_dout(img_input_data_strea_1_dout),
    .img_input_data_strea_1_empty_n(img_input_data_strea_1_empty_n),
    .img_input_data_strea_1_read(Loop_loop_height_pro_2_U0_img_input_data_strea_1_read),
    .img_input_data_strea_2_dout(img_input_data_strea_2_dout),
    .img_input_data_strea_2_empty_n(img_input_data_strea_2_empty_n),
    .img_input_data_strea_2_read(Loop_loop_height_pro_2_U0_img_input_data_strea_2_read),
    .img_crop_data_stream_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_din),
    .img_crop_data_stream_full_n(img_crop_data_stream_full_n),
    .img_crop_data_stream_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_write),
    .img_crop_data_stream_1_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_1_din),
    .img_crop_data_stream_1_full_n(img_crop_data_stream_1_full_n),
    .img_crop_data_stream_1_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_1_write),
    .img_crop_data_stream_2_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_2_din),
    .img_crop_data_stream_2_full_n(img_crop_data_stream_2_full_n),
    .img_crop_data_stream_2_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_2_write)
);

Loop_loop_height_pro_1 Loop_loop_height_pro_1_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_loop_height_pro_1_U0_ap_start),
    .start_full_n(start_for_video_scale_U0_full_n),
    .ap_done(Loop_loop_height_pro_1_U0_ap_done),
    .ap_continue(Loop_loop_height_pro_1_U0_ap_continue),
    .ap_idle(Loop_loop_height_pro_1_U0_ap_idle),
    .ap_ready(Loop_loop_height_pro_1_U0_ap_ready),
    .start_out(Loop_loop_height_pro_1_U0_start_out),
    .start_write(Loop_loop_height_pro_1_U0_start_write),
    .img_crop_data_stream_0_V_dout(img_crop_data_stream_dout),
    .img_crop_data_stream_0_V_empty_n(img_crop_data_stream_empty_n),
    .img_crop_data_stream_0_V_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_0_V_read),
    .img_crop_data_stream_1_V_dout(img_crop_data_stream_1_dout),
    .img_crop_data_stream_1_V_empty_n(img_crop_data_stream_1_empty_n),
    .img_crop_data_stream_1_V_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_1_V_read),
    .img_crop_data_stream_2_V_dout(img_crop_data_stream_2_dout),
    .img_crop_data_stream_2_V_empty_n(img_crop_data_stream_2_empty_n),
    .img_crop_data_stream_2_V_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_2_V_read),
    .img_nogamma_data_stream_0_V_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_din),
    .img_nogamma_data_stream_0_V_full_n(img_nogamma_data_str_full_n),
    .img_nogamma_data_stream_0_V_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_write),
    .img_nogamma_data_stream_1_V_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_din),
    .img_nogamma_data_stream_1_V_full_n(img_nogamma_data_str_1_full_n),
    .img_nogamma_data_stream_1_V_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_write),
    .img_nogamma_data_stream_2_V_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_din),
    .img_nogamma_data_stream_2_V_full_n(img_nogamma_data_str_2_full_n),
    .img_nogamma_data_stream_2_V_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_write)
);

video_scale video_scale_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(video_scale_U0_ap_start),
    .start_full_n(start_for_brightness_color_adj_U0_full_n),
    .ap_done(video_scale_U0_ap_done),
    .ap_continue(video_scale_U0_ap_continue),
    .ap_idle(video_scale_U0_ap_idle),
    .ap_ready(video_scale_U0_ap_ready),
    .start_out(video_scale_U0_start_out),
    .start_write(video_scale_U0_start_write),
    .src_data_stream_0_V_dout(img_nogamma_data_str_dout),
    .src_data_stream_0_V_empty_n(img_nogamma_data_str_empty_n),
    .src_data_stream_0_V_read(video_scale_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_nogamma_data_str_1_dout),
    .src_data_stream_1_V_empty_n(img_nogamma_data_str_1_empty_n),
    .src_data_stream_1_V_read(video_scale_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_nogamma_data_str_2_dout),
    .src_data_stream_2_V_empty_n(img_nogamma_data_str_2_empty_n),
    .src_data_stream_2_V_read(video_scale_U0_src_data_stream_2_V_read),
    .dst_data_stream_0_V_din(video_scale_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(img_scaled_data_stre_full_n),
    .dst_data_stream_0_V_write(video_scale_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(video_scale_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(img_scaled_data_stre_1_full_n),
    .dst_data_stream_1_V_write(video_scale_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(video_scale_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(img_scaled_data_stre_2_full_n),
    .dst_data_stream_2_V_write(video_scale_U0_dst_data_stream_2_V_write)
);

brightness_color_adj brightness_color_adj_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(brightness_color_adj_U0_ap_start),
    .start_full_n(start_for_Loop_loop_height_pro_U0_full_n),
    .ap_done(brightness_color_adj_U0_ap_done),
    .ap_continue(brightness_color_adj_U0_ap_continue),
    .ap_idle(brightness_color_adj_U0_ap_idle),
    .ap_ready(brightness_color_adj_U0_ap_ready),
    .start_out(brightness_color_adj_U0_start_out),
    .start_write(brightness_color_adj_U0_start_write),
    .src_data_stream_0_V_dout(img_scaled_data_stre_dout),
    .src_data_stream_0_V_empty_n(img_scaled_data_stre_empty_n),
    .src_data_stream_0_V_read(brightness_color_adj_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(img_scaled_data_stre_1_dout),
    .src_data_stream_1_V_empty_n(img_scaled_data_stre_1_empty_n),
    .src_data_stream_1_V_read(brightness_color_adj_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(img_scaled_data_stre_2_dout),
    .src_data_stream_2_V_empty_n(img_scaled_data_stre_2_empty_n),
    .src_data_stream_2_V_read(brightness_color_adj_U0_src_data_stream_2_V_read),
    .dst_data_stream_0_V_din(brightness_color_adj_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(img_adjusted_data_st_full_n),
    .dst_data_stream_0_V_write(brightness_color_adj_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(brightness_color_adj_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(img_adjusted_data_st_1_full_n),
    .dst_data_stream_1_V_write(brightness_color_adj_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(brightness_color_adj_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(img_adjusted_data_st_2_full_n),
    .dst_data_stream_2_V_write(brightness_color_adj_U0_dst_data_stream_2_V_write),
    .brightness_index_V(brightness_V),
    .color_correct_V(color_correct_V)
);

Loop_loop_height_pro Loop_loop_height_pro_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_loop_height_pro_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Loop_loop_height_pro_U0_ap_done),
    .ap_continue(Loop_loop_height_pro_U0_ap_continue),
    .ap_idle(Loop_loop_height_pro_U0_ap_idle),
    .ap_ready(Loop_loop_height_pro_U0_ap_ready),
    .start_out(Loop_loop_height_pro_U0_start_out),
    .start_write(Loop_loop_height_pro_U0_start_write),
    .img_adjusted_data_stream_0_V_dout(img_adjusted_data_st_dout),
    .img_adjusted_data_stream_0_V_empty_n(img_adjusted_data_st_empty_n),
    .img_adjusted_data_stream_0_V_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_0_V_read),
    .img_adjusted_data_stream_1_V_dout(img_adjusted_data_st_1_dout),
    .img_adjusted_data_stream_1_V_empty_n(img_adjusted_data_st_1_empty_n),
    .img_adjusted_data_stream_1_V_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_1_V_read),
    .img_adjusted_data_stream_2_V_dout(img_adjusted_data_st_2_dout),
    .img_adjusted_data_stream_2_V_empty_n(img_adjusted_data_st_2_empty_n),
    .img_adjusted_data_stream_2_V_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_2_V_read),
    .img_out_data_stream_0_V_din(Loop_loop_height_pro_U0_img_out_data_stream_0_V_din),
    .img_out_data_stream_0_V_full_n(img_out_data_stream_s_full_n),
    .img_out_data_stream_0_V_write(Loop_loop_height_pro_U0_img_out_data_stream_0_V_write),
    .img_out_data_stream_1_V_din(Loop_loop_height_pro_U0_img_out_data_stream_1_V_din),
    .img_out_data_stream_1_V_full_n(img_out_data_stream_1_full_n),
    .img_out_data_stream_1_V_write(Loop_loop_height_pro_U0_img_out_data_stream_1_V_write),
    .img_out_data_stream_2_V_din(Loop_loop_height_pro_U0_img_out_data_stream_2_V_din),
    .img_out_data_stream_2_V_full_n(img_out_data_stream_2_full_n),
    .img_out_data_stream_2_V_write(Loop_loop_height_pro_U0_img_out_data_stream_2_V_write)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_data_stream_0_V_dout(img_out_data_stream_s_dout),
    .img_data_stream_0_V_empty_n(img_out_data_stream_s_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(img_out_data_stream_1_dout),
    .img_data_stream_1_V_empty_n(img_out_data_stream_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(img_out_data_stream_2_dout),
    .img_data_stream_2_V_empty_n(img_out_data_stream_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .stream_out_TDATA(Mat2AXIvideo_U0_stream_out_TDATA),
    .stream_out_TVALID(Mat2AXIvideo_U0_stream_out_TVALID),
    .stream_out_TREADY(stream_out_TREADY),
    .stream_out_TKEEP(Mat2AXIvideo_U0_stream_out_TKEEP),
    .stream_out_TSTRB(Mat2AXIvideo_U0_stream_out_TSTRB),
    .stream_out_TUSER(Mat2AXIvideo_U0_stream_out_TUSER),
    .stream_out_TLAST(Mat2AXIvideo_U0_stream_out_TLAST),
    .stream_out_TID(Mat2AXIvideo_U0_stream_out_TID),
    .stream_out_TDEST(Mat2AXIvideo_U0_stream_out_TDEST)
);

fifo_w12_d2_A img_input_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_input_rows_V_out_din),
    .if_full_n(img_input_rows_V_c_full_n),
    .if_write(Block_proc_U0_img_input_rows_V_out_write),
    .if_dout(img_input_rows_V_c_dout),
    .if_empty_n(img_input_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w12_d2_A img_input_rows_V_c20_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_input_rows_V_out1_din),
    .if_full_n(img_input_rows_V_c20_full_n),
    .if_write(Block_proc_U0_img_input_rows_V_out1_write),
    .if_dout(img_input_rows_V_c20_dout),
    .if_empty_n(img_input_rows_V_c20_empty_n),
    .if_read(Block_proc55_U0_img_input_rows_V_read)
);

fifo_w12_d2_A img_input_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc_U0_img_input_cols_V_out_din),
    .if_full_n(img_input_cols_V_c_full_n),
    .if_write(Block_proc_U0_img_input_cols_V_out_write),
    .if_dout(img_input_cols_V_c_dout),
    .if_empty_n(img_input_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w8_d2_A img_input_data_strea_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(img_input_data_strea_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(img_input_data_strea_dout),
    .if_empty_n(img_input_data_strea_empty_n),
    .if_read(Loop_loop_height_pro_2_U0_img_input_data_strea_read)
);

fifo_w8_d2_A img_input_data_strea_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(img_input_data_strea_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(img_input_data_strea_1_dout),
    .if_empty_n(img_input_data_strea_1_empty_n),
    .if_read(Loop_loop_height_pro_2_U0_img_input_data_strea_1_read)
);

fifo_w8_d2_A img_input_data_strea_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(img_input_data_strea_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(img_input_data_strea_2_dout),
    .if_empty_n(img_input_data_strea_2_empty_n),
    .if_read(Loop_loop_height_pro_2_U0_img_input_data_strea_2_read)
);

fifo_w12_d2_A img_input_cols_V_c20_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(img_input_cols_V_c20_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(img_input_cols_V_c20_dout),
    .if_empty_n(img_input_cols_V_c20_empty_n),
    .if_read(Loop_loop_height_pro_2_U0_img_input_cols_V_c20_read)
);

fifo_w12_d2_A extLd_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_proc55_U0_ap_return),
    .if_full_n(extLd_loc_channel_full_n),
    .if_write(Block_proc55_U0_ap_done),
    .if_dout(extLd_loc_channel_dout),
    .if_empty_n(extLd_loc_channel_empty_n),
    .if_read(Loop_loop_height_pro_2_U0_ap_ready)
);

fifo_w8_d2_A img_crop_data_stream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_din),
    .if_full_n(img_crop_data_stream_full_n),
    .if_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_write),
    .if_dout(img_crop_data_stream_dout),
    .if_empty_n(img_crop_data_stream_empty_n),
    .if_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_0_V_read)
);

fifo_w8_d2_A img_crop_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_1_din),
    .if_full_n(img_crop_data_stream_1_full_n),
    .if_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_1_write),
    .if_dout(img_crop_data_stream_1_dout),
    .if_empty_n(img_crop_data_stream_1_empty_n),
    .if_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_1_V_read)
);

fifo_w8_d2_A img_crop_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_2_U0_img_crop_data_stream_2_din),
    .if_full_n(img_crop_data_stream_2_full_n),
    .if_write(Loop_loop_height_pro_2_U0_img_crop_data_stream_2_write),
    .if_dout(img_crop_data_stream_2_dout),
    .if_empty_n(img_crop_data_stream_2_empty_n),
    .if_read(Loop_loop_height_pro_1_U0_img_crop_data_stream_2_V_read)
);

fifo_w32_d2_A img_nogamma_data_str_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_din),
    .if_full_n(img_nogamma_data_str_full_n),
    .if_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_0_V_write),
    .if_dout(img_nogamma_data_str_dout),
    .if_empty_n(img_nogamma_data_str_empty_n),
    .if_read(video_scale_U0_src_data_stream_0_V_read)
);

fifo_w32_d2_A img_nogamma_data_str_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_din),
    .if_full_n(img_nogamma_data_str_1_full_n),
    .if_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_1_V_write),
    .if_dout(img_nogamma_data_str_1_dout),
    .if_empty_n(img_nogamma_data_str_1_empty_n),
    .if_read(video_scale_U0_src_data_stream_1_V_read)
);

fifo_w32_d2_A img_nogamma_data_str_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_din),
    .if_full_n(img_nogamma_data_str_2_full_n),
    .if_write(Loop_loop_height_pro_1_U0_img_nogamma_data_stream_2_V_write),
    .if_dout(img_nogamma_data_str_2_dout),
    .if_empty_n(img_nogamma_data_str_2_empty_n),
    .if_read(video_scale_U0_src_data_stream_2_V_read)
);

fifo_w32_d2_A img_scaled_data_stre_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(video_scale_U0_dst_data_stream_0_V_din),
    .if_full_n(img_scaled_data_stre_full_n),
    .if_write(video_scale_U0_dst_data_stream_0_V_write),
    .if_dout(img_scaled_data_stre_dout),
    .if_empty_n(img_scaled_data_stre_empty_n),
    .if_read(brightness_color_adj_U0_src_data_stream_0_V_read)
);

fifo_w32_d2_A img_scaled_data_stre_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(video_scale_U0_dst_data_stream_1_V_din),
    .if_full_n(img_scaled_data_stre_1_full_n),
    .if_write(video_scale_U0_dst_data_stream_1_V_write),
    .if_dout(img_scaled_data_stre_1_dout),
    .if_empty_n(img_scaled_data_stre_1_empty_n),
    .if_read(brightness_color_adj_U0_src_data_stream_1_V_read)
);

fifo_w32_d2_A img_scaled_data_stre_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(video_scale_U0_dst_data_stream_2_V_din),
    .if_full_n(img_scaled_data_stre_2_full_n),
    .if_write(video_scale_U0_dst_data_stream_2_V_write),
    .if_dout(img_scaled_data_stre_2_dout),
    .if_empty_n(img_scaled_data_stre_2_empty_n),
    .if_read(brightness_color_adj_U0_src_data_stream_2_V_read)
);

fifo_w32_d2_A img_adjusted_data_st_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(brightness_color_adj_U0_dst_data_stream_0_V_din),
    .if_full_n(img_adjusted_data_st_full_n),
    .if_write(brightness_color_adj_U0_dst_data_stream_0_V_write),
    .if_dout(img_adjusted_data_st_dout),
    .if_empty_n(img_adjusted_data_st_empty_n),
    .if_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_0_V_read)
);

fifo_w32_d2_A img_adjusted_data_st_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(brightness_color_adj_U0_dst_data_stream_1_V_din),
    .if_full_n(img_adjusted_data_st_1_full_n),
    .if_write(brightness_color_adj_U0_dst_data_stream_1_V_write),
    .if_dout(img_adjusted_data_st_1_dout),
    .if_empty_n(img_adjusted_data_st_1_empty_n),
    .if_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_1_V_read)
);

fifo_w32_d2_A img_adjusted_data_st_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(brightness_color_adj_U0_dst_data_stream_2_V_din),
    .if_full_n(img_adjusted_data_st_2_full_n),
    .if_write(brightness_color_adj_U0_dst_data_stream_2_V_write),
    .if_dout(img_adjusted_data_st_2_dout),
    .if_empty_n(img_adjusted_data_st_2_empty_n),
    .if_read(Loop_loop_height_pro_U0_img_adjusted_data_stream_2_V_read)
);

fifo_w8_d2_A img_out_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_U0_img_out_data_stream_0_V_din),
    .if_full_n(img_out_data_stream_s_full_n),
    .if_write(Loop_loop_height_pro_U0_img_out_data_stream_0_V_write),
    .if_dout(img_out_data_stream_s_dout),
    .if_empty_n(img_out_data_stream_s_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A img_out_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_U0_img_out_data_stream_1_V_din),
    .if_full_n(img_out_data_stream_1_full_n),
    .if_write(Loop_loop_height_pro_U0_img_out_data_stream_1_V_write),
    .if_dout(img_out_data_stream_1_dout),
    .if_empty_n(img_out_data_stream_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A img_out_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Loop_loop_height_pro_U0_img_out_data_stream_2_V_din),
    .if_full_n(img_out_data_stream_2_full_n),
    .if_write(Loop_loop_height_pro_U0_img_out_data_stream_2_V_write),
    .if_dout(img_out_data_stream_2_dout),
    .if_empty_n(img_out_data_stream_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

start_for_Block_pjbC start_for_Block_pjbC_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Block_proc55_U0_din),
    .if_full_n(start_for_Block_proc55_U0_full_n),
    .if_write(Block_proc_U0_start_write),
    .if_dout(start_for_Block_proc55_U0_dout),
    .if_empty_n(start_for_Block_proc55_U0_empty_n),
    .if_read(Block_proc55_U0_ap_ready)
);

start_for_Loop_lokbM start_for_Loop_lokbM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_loop_height_pro_1_U0_din),
    .if_full_n(start_for_Loop_loop_height_pro_1_U0_full_n),
    .if_write(Loop_loop_height_pro_2_U0_start_write),
    .if_dout(start_for_Loop_loop_height_pro_1_U0_dout),
    .if_empty_n(start_for_Loop_loop_height_pro_1_U0_empty_n),
    .if_read(Loop_loop_height_pro_1_U0_ap_ready)
);

start_for_video_slbW start_for_video_slbW_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_video_scale_U0_din),
    .if_full_n(start_for_video_scale_U0_full_n),
    .if_write(Loop_loop_height_pro_1_U0_start_write),
    .if_dout(start_for_video_scale_U0_dout),
    .if_empty_n(start_for_video_scale_U0_empty_n),
    .if_read(video_scale_U0_ap_ready)
);

start_for_brightnmb6 start_for_brightnmb6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_brightness_color_adj_U0_din),
    .if_full_n(start_for_brightness_color_adj_U0_full_n),
    .if_write(video_scale_U0_start_write),
    .if_dout(start_for_brightness_color_adj_U0_dout),
    .if_empty_n(start_for_brightness_color_adj_U0_empty_n),
    .if_read(brightness_color_adj_U0_ap_ready)
);

start_for_Loop_loncg start_for_Loop_loncg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_loop_height_pro_U0_din),
    .if_full_n(start_for_Loop_loop_height_pro_U0_full_n),
    .if_write(brightness_color_adj_U0_start_write),
    .if_dout(start_for_Loop_loop_height_pro_U0_dout),
    .if_empty_n(start_for_Loop_loop_height_pro_U0_empty_n),
    .if_read(Loop_loop_height_pro_U0_ap_ready)
);

start_for_Mat2AXIocq start_for_Mat2AXIocq_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Loop_loop_height_pro_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = 1'b1;

assign AXIvideo2Mat_U0_start_full_n = 1'b1;

assign AXIvideo2Mat_U0_start_write = 1'b0;

assign Block_proc55_U0_ap_continue = extLd_loc_channel_full_n;

assign Block_proc55_U0_ap_start = start_for_Block_proc55_U0_empty_n;

assign Block_proc55_U0_start_full_n = 1'b1;

assign Block_proc55_U0_start_write = 1'b0;

assign Block_proc_U0_ap_continue = 1'b1;

assign Block_proc_U0_ap_start = 1'b1;

assign Loop_loop_height_pro_1_U0_ap_continue = 1'b1;

assign Loop_loop_height_pro_1_U0_ap_start = start_for_Loop_loop_height_pro_1_U0_empty_n;

assign Loop_loop_height_pro_2_U0_ap_continue = 1'b1;

assign Loop_loop_height_pro_2_U0_ap_start = extLd_loc_channel_empty_n;

assign Loop_loop_height_pro_U0_ap_continue = 1'b1;

assign Loop_loop_height_pro_U0_ap_start = start_for_Loop_loop_height_pro_U0_empty_n;

assign Mat2AXIvideo_U0_ap_continue = 1'b1;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign ap_channel_done_extLd_loc_channel = Block_proc55_U0_ap_done;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_continue = 1'b0;

assign brightness_color_adj_U0_ap_continue = 1'b1;

assign brightness_color_adj_U0_ap_start = start_for_brightness_color_adj_U0_empty_n;

assign start_for_Block_proc55_U0_din = 1'b1;

assign start_for_Loop_loop_height_pro_1_U0_din = 1'b1;

assign start_for_Loop_loop_height_pro_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_brightness_color_adj_U0_din = 1'b1;

assign start_for_video_scale_U0_din = 1'b1;

assign stream_in_TREADY = AXIvideo2Mat_U0_stream_in_TREADY;

assign stream_out_TDATA = Mat2AXIvideo_U0_stream_out_TDATA;

assign stream_out_TDEST = Mat2AXIvideo_U0_stream_out_TDEST;

assign stream_out_TID = Mat2AXIvideo_U0_stream_out_TID;

assign stream_out_TKEEP = Mat2AXIvideo_U0_stream_out_TKEEP;

assign stream_out_TLAST = Mat2AXIvideo_U0_stream_out_TLAST;

assign stream_out_TSTRB = Mat2AXIvideo_U0_stream_out_TSTRB;

assign stream_out_TUSER = Mat2AXIvideo_U0_stream_out_TUSER;

assign stream_out_TVALID = Mat2AXIvideo_U0_stream_out_TVALID;

assign video_scale_U0_ap_continue = 1'b1;

assign video_scale_U0_ap_start = start_for_video_scale_U0_empty_n;

endmodule //hls_video_processor
