-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Loop_loop_height_pro_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    img_input_cols_V_c20_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    img_input_cols_V_c20_empty_n : IN STD_LOGIC;
    img_input_cols_V_c20_read : OUT STD_LOGIC;
    extLd_loc_channel : IN STD_LOGIC_VECTOR (11 downto 0);
    img_input_data_strea_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_input_data_strea_empty_n : IN STD_LOGIC;
    img_input_data_strea_read : OUT STD_LOGIC;
    img_input_data_strea_1_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_input_data_strea_1_empty_n : IN STD_LOGIC;
    img_input_data_strea_1_read : OUT STD_LOGIC;
    img_input_data_strea_2_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    img_input_data_strea_2_empty_n : IN STD_LOGIC;
    img_input_data_strea_2_read : OUT STD_LOGIC;
    img_crop_data_stream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_crop_data_stream_full_n : IN STD_LOGIC;
    img_crop_data_stream_write : OUT STD_LOGIC;
    img_crop_data_stream_1_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_crop_data_stream_1_full_n : IN STD_LOGIC;
    img_crop_data_stream_1_write : OUT STD_LOGIC;
    img_crop_data_stream_2_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_crop_data_stream_2_full_n : IN STD_LOGIC;
    img_crop_data_stream_2_write : OUT STD_LOGIC );
end;


architecture behav of Loop_loop_height_pro_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_3B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111011";
    constant ap_const_lv32_3FC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111111100";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal img_input_cols_V_c20_blk_n : STD_LOGIC;
    signal img_input_data_strea_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal img_input_data_strea_1_blk_n : STD_LOGIC;
    signal img_input_data_strea_2_blk_n : STD_LOGIC;
    signal img_crop_data_stream_blk_n : STD_LOGIC;
    signal or_cond_i_i_i_i_reg_211 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_crop_data_stream_1_blk_n : STD_LOGIC;
    signal img_crop_data_stream_2_blk_n : STD_LOGIC;
    signal t_V_4_reg_133 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read_cast_i_fu_144_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_read_cast_i_reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_V_fu_148_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_V_reg_197 : STD_LOGIC_VECTOR (31 downto 0);
    signal exitcond89_i_i_i_i_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal r_V_fu_157_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal r_V_reg_206 : STD_LOGIC_VECTOR (31 downto 0);
    signal or_cond_i_i_i_i_fu_175_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_i_i_i_i_fu_181_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal c_V_fu_186_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal t_V_reg_122 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_i_i_i_fu_163_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_i_i_59_fu_169_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    t_V_4_reg_133_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_i_i_i_i_fu_181_p2 = ap_const_lv1_0))) then 
                t_V_4_reg_133 <= c_V_fu_186_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_0))) then 
                t_V_4_reg_133 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_reg_122_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                t_V_reg_122 <= r_V_reg_206;
            elsif ((not(((img_input_cols_V_c20_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                t_V_reg_122 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((img_input_cols_V_c20_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_V_reg_197 <= cols_V_fu_148_p1;
                p_read_cast_i_reg_192 <= p_read_cast_i_fu_144_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_0))) then
                or_cond_i_i_i_i_reg_211 <= or_cond_i_i_i_i_fu_175_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                r_V_reg_206 <= r_V_fu_157_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, img_input_cols_V_c20_empty_n, exitcond89_i_i_i_i_fu_152_p2, ap_CS_fsm_state2, exitcond_i_i_i_i_fu_181_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((img_input_cols_V_c20_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((exitcond_i_i_i_i_fu_181_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((exitcond_i_i_i_i_fu_181_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(img_input_data_strea_empty_n, img_input_data_strea_1_empty_n, img_input_data_strea_2_empty_n, img_crop_data_stream_full_n, img_crop_data_stream_1_full_n, img_crop_data_stream_2_full_n, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((img_input_data_strea_2_empty_n = ap_const_logic_0) or (img_input_data_strea_1_empty_n = ap_const_logic_0) or (img_input_data_strea_empty_n = ap_const_logic_0) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_2_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_1_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_full_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(img_input_data_strea_empty_n, img_input_data_strea_1_empty_n, img_input_data_strea_2_empty_n, img_crop_data_stream_full_n, img_crop_data_stream_1_full_n, img_crop_data_stream_2_full_n, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((img_input_data_strea_2_empty_n = ap_const_logic_0) or (img_input_data_strea_1_empty_n = ap_const_logic_0) or (img_input_data_strea_empty_n = ap_const_logic_0) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_2_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_1_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_full_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(img_input_data_strea_empty_n, img_input_data_strea_1_empty_n, img_input_data_strea_2_empty_n, img_crop_data_stream_full_n, img_crop_data_stream_1_full_n, img_crop_data_stream_2_full_n, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and ((img_input_data_strea_2_empty_n = ap_const_logic_0) or (img_input_data_strea_1_empty_n = ap_const_logic_0) or (img_input_data_strea_empty_n = ap_const_logic_0) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_2_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_1_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_full_n = ap_const_logic_0))));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, img_input_cols_V_c20_empty_n)
    begin
                ap_block_state1 <= ((img_input_cols_V_c20_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(img_input_data_strea_empty_n, img_input_data_strea_1_empty_n, img_input_data_strea_2_empty_n, img_crop_data_stream_full_n, img_crop_data_stream_1_full_n, img_crop_data_stream_2_full_n, or_cond_i_i_i_i_reg_211)
    begin
                ap_block_state4_pp0_stage0_iter1 <= ((img_input_data_strea_2_empty_n = ap_const_logic_0) or (img_input_data_strea_1_empty_n = ap_const_logic_0) or (img_input_data_strea_empty_n = ap_const_logic_0) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_2_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_1_full_n = ap_const_logic_0)) or ((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (img_crop_data_stream_full_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(exitcond_i_i_i_i_fu_181_p2)
    begin
        if ((exitcond_i_i_i_i_fu_181_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, exitcond89_i_i_i_i_fu_152_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;
    c_V_fu_186_p2 <= std_logic_vector(unsigned(t_V_4_reg_133) + unsigned(ap_const_lv32_1));
        cols_V_fu_148_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(img_input_cols_V_c20_dout),32));

    exitcond89_i_i_i_i_fu_152_p2 <= "1" when (t_V_reg_122 = p_read_cast_i_reg_192) else "0";
    exitcond_i_i_i_i_fu_181_p2 <= "1" when (t_V_4_reg_133 = cols_V_reg_197) else "0";

    img_crop_data_stream_1_blk_n_assign_proc : process(img_crop_data_stream_1_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, or_cond_i_i_i_i_reg_211)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_crop_data_stream_1_blk_n <= img_crop_data_stream_1_full_n;
        else 
            img_crop_data_stream_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_crop_data_stream_1_din <= img_input_data_strea_1_dout;

    img_crop_data_stream_1_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211, ap_block_pp0_stage0_11001)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_crop_data_stream_1_write <= ap_const_logic_1;
        else 
            img_crop_data_stream_1_write <= ap_const_logic_0;
        end if; 
    end process;


    img_crop_data_stream_2_blk_n_assign_proc : process(img_crop_data_stream_2_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, or_cond_i_i_i_i_reg_211)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_crop_data_stream_2_blk_n <= img_crop_data_stream_2_full_n;
        else 
            img_crop_data_stream_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_crop_data_stream_2_din <= img_input_data_strea_2_dout;

    img_crop_data_stream_2_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211, ap_block_pp0_stage0_11001)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_crop_data_stream_2_write <= ap_const_logic_1;
        else 
            img_crop_data_stream_2_write <= ap_const_logic_0;
        end if; 
    end process;


    img_crop_data_stream_blk_n_assign_proc : process(img_crop_data_stream_full_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, or_cond_i_i_i_i_reg_211)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_crop_data_stream_blk_n <= img_crop_data_stream_full_n;
        else 
            img_crop_data_stream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_crop_data_stream_din <= img_input_data_strea_dout;

    img_crop_data_stream_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, or_cond_i_i_i_i_reg_211, ap_block_pp0_stage0_11001)
    begin
        if (((or_cond_i_i_i_i_reg_211 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_crop_data_stream_write <= ap_const_logic_1;
        else 
            img_crop_data_stream_write <= ap_const_logic_0;
        end if; 
    end process;


    img_input_cols_V_c20_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_input_cols_V_c20_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_input_cols_V_c20_blk_n <= img_input_cols_V_c20_empty_n;
        else 
            img_input_cols_V_c20_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_input_cols_V_c20_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_input_cols_V_c20_empty_n)
    begin
        if ((not(((img_input_cols_V_c20_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_input_cols_V_c20_read <= ap_const_logic_1;
        else 
            img_input_cols_V_c20_read <= ap_const_logic_0;
        end if; 
    end process;


    img_input_data_strea_1_blk_n_assign_proc : process(img_input_data_strea_1_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_input_data_strea_1_blk_n <= img_input_data_strea_1_empty_n;
        else 
            img_input_data_strea_1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_input_data_strea_1_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_input_data_strea_1_read <= ap_const_logic_1;
        else 
            img_input_data_strea_1_read <= ap_const_logic_0;
        end if; 
    end process;


    img_input_data_strea_2_blk_n_assign_proc : process(img_input_data_strea_2_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_input_data_strea_2_blk_n <= img_input_data_strea_2_empty_n;
        else 
            img_input_data_strea_2_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_input_data_strea_2_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_input_data_strea_2_read <= ap_const_logic_1;
        else 
            img_input_data_strea_2_read <= ap_const_logic_0;
        end if; 
    end process;


    img_input_data_strea_blk_n_assign_proc : process(img_input_data_strea_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            img_input_data_strea_blk_n <= img_input_data_strea_empty_n;
        else 
            img_input_data_strea_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_input_data_strea_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            img_input_data_strea_read <= ap_const_logic_1;
        else 
            img_input_data_strea_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(exitcond89_i_i_i_i_fu_152_p2, ap_CS_fsm_state2)
    begin
        if (((exitcond89_i_i_i_i_fu_152_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    or_cond_i_i_i_i_fu_175_p2 <= (tmp_i_i_i_fu_163_p2 and tmp_i_i_i_59_fu_169_p2);
        p_read_cast_i_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(extLd_loc_channel),32));

    r_V_fu_157_p2 <= std_logic_vector(unsigned(t_V_reg_122) + unsigned(ap_const_lv32_1));

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_i_i_i_59_fu_169_p2 <= "1" when (unsigned(t_V_reg_122) < unsigned(ap_const_lv32_3FC)) else "0";
    tmp_i_i_i_fu_163_p2 <= "1" when (unsigned(t_V_reg_122) > unsigned(ap_const_lv32_3B)) else "0";
end behav;
